info:
  contact: {}
paths:
  /ping:
    get:
      description: return hello world json format content
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: say hello world
      tags:
      - system
swagger: "2.0"
